# Etapa de compilación
FROM node:16.13-alpine as builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

# Etapa de producción
FROM nginx:1.21-alpine

COPY --from=builder /app/dist/tiendaonlinedeportiva /usr/share/nginx/html
COPY /nginx.conf  /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
